[greeter]
background=/usr/share/backgrounds/lightos-wallpaper.png
theme-name=LightOS-Dark
icon-theme-name=Papirus-Dark
cursor-theme-name=Adwaita
font-name=DejaVu Sans 10
indicators=~host;~spacer;~clock;~session;~language;~power
clock-format=%H:%M