---
defaultFileSystemType: "ext4"
allowManualPartitioning: true
efi:
    mountPoint: "/boot/efi"
    recommendedSize: 300MiB
    minimumSize: 32MiB
    label: "EFI"
userSwapChoices:
    - file
initialSwapChoice: file
lvm:
    enable: false