---
defaultGroups:
    - users
    - sudo
    - audio
    - video
    - cdrom
    - plugdev
    - netdev
    - input
    - bluetooth
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
sudoersConfigureWithGroup: false
setRootPassword: true
doReusePassword: true
passwordRequirements:
    nonempty: true
    minLength: -1
    maxLength: -1
    libpwquality:
        - minlen=0
        - minclass=0
allowWeakPasswords: true
allowWeakPasswordsDefault: true
user:
    shell: /bin/bash
    forbidden_names: [ root ]
hostname:
    location: EtcFile
    writeHostsFile: true
    template: "${first}-${product}"
    forbidden_names: [ localhost ]
presets:
    fullName:
        editable: true
    loginName:
        editable: true