---
modules-search:
    - local
    - /etc/calamares/modules

instances:
    - id:       welcome
      module:   welcome
      config:   welcome.conf

    - id:       locale
      module:   locale
      config:   locale.conf

    - id:       keyboard
      module:   keyboard
      config:   keyboard.conf

    - id:       users
      module:   users
      config:   users.conf

    - id:       partition
      module:   partition
      config:   partition.conf

    - id:       shellprocess-copy
      module:   shellprocess
      config:   shellprocess-copy.conf

    - id:       fstab
      module:   fstab
      config:   fstab.conf

    - id:       shellprocess-post
      module:   shellprocess
      config:   shellprocess-post.conf

    - id:       networkcfg
      module:   networkcfg
      config:   networkcfg.conf

    - id:       bootloader
      module:   bootloader
      config:   bootloader.conf

    - id:       finished
      module:   finished
      config:   finished.conf

sequence:
    - show:
        - welcome
        - locale
        - keyboard
        - users
        - partition
        - finished
    - install:
        - partition
        - shellprocess-copy
        - fstab
        - users
        - shellprocess-post
        - networkcfg
        - bootloader
    - postinstall:
        - finished

branding: lightos